server:
  port: 8081

spring:
  application:
    name: komando-notification-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092} # if running on the app on Docker, use kafka:9092 ==============================
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: org.russel.komandosb.data.model.event

firebase:
  service-account-path: C:\Users\russel\Documents\komando\komandobackend\serviceAccountKey.json
